# Generated by Django 5.0.3 on 2024-03-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='hidden',
            field=models.BooleanField(default=False, help_text='是否隐藏', verbose_name='是否隐藏'),
        ),
    ]
