# Generated by Django 5.0.3 on 2024-04-02 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userprofile_add_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='add_time',
            field=models.DateField(default=datetime.date.today, help_text='添加时间', verbose_name='添加时间'),
        ),
    ]
