# Generated by Django 5.0.3 on 2024-03-18 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='sub_menu',
            field=models.ForeignKey(blank=True, help_text='上级菜单', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_menu', to='user.menu', verbose_name='上级菜单'),
        ),
    ]
