# Generated by Django 5.0.3 on 2024-04-03 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_userprofile_add_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(help_text='家庭地址', max_length=50, null=True, verbose_name='家庭地址'),
        ),
    ]
