# Generated by Django 5.0.3 on 2024-04-05 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userprofile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='method_type',
            field=models.CharField(help_text='方法类型', max_length=30, null=True, verbose_name='方法类型'),
        ),
    ]
