# Generated by Django 5.0.1 on 2024-02-19 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_delete_verifycode_alter_emailverifycode_add_time'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='smsverifycode',
            table='SmsVerifyCode',
        ),
    ]
