# Generated by Django 5.0.1 on 2024-02-19 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_smsverifycode_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='smsverifycode',
            table=None,
        ),
    ]
