# Generated by Django 5.0.3 on 2024-04-06 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_rename_method_type_permission_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='router',
            field=models.ForeignKey(help_text='权限', on_delete=django.db.models.deletion.CASCADE, to='user.router', verbose_name='权限'),
        ),
    ]
