# Generated by Django 5.0.3 on 2024-04-07 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_permission_router'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='router',
            field=models.ForeignKey(help_text='权限', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.router', verbose_name='权限'),
        ),
    ]
