# Generated by Django 5.0.1 on 2024-02-21 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='菜单名', max_length=30, verbose_name='菜单名')),
                ('icon', models.CharField(max_length=50, verbose_name='图标')),
                ('url_name', models.CharField(default='', max_length=50, verbose_name='图标')),
                ('parent_menu', models.ForeignKey(blank=True, help_text='父菜单', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_menu', to='user.menu', verbose_name='父类菜单')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='权限名称', max_length=30, verbose_name='权限名称')),
                ('method_type', models.IntegerField(choices=[(1, 'GET'), (2, 'POST'), (3, 'DELETE'), (4, 'PUT'), (5, 'PATCH')], help_text='方法', verbose_name='方法类型')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_id', to='user.menu', verbose_name='菜单')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='名称')),
                ('role', models.IntegerField(choices=[(1, 'admin'), (2, 'teacher'), (3, 'student')], help_text='角色', verbose_name='角色')),
                ('permission', models.ManyToManyField(related_name='permission_id', to='user.permission', verbose_name='权限')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='role_id', to='user.role', verbose_name='角色'),
        ),
    ]
