# Generated by Django 5.0.3 on 2024-04-08 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_permission_router'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='desc',
            field=models.CharField(help_text='描述', max_length=100, null=True, verbose_name='描述'),
        ),
    ]
