# Generated by Django 5.0.1 on 2024-02-22 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_remove_userprofile_role_userprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.ManyToManyField(related_name='role_id', to='user.role', verbose_name='角色'),
        ),
    ]
