# Generated by Django 5.0.2 on 2024-02-23 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_remove_userprofile_role_userprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='name',
        ),
    ]
