# Generated by Django 5.0.2 on 2024-02-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_remove_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='method_type',
            field=models.IntegerField(choices=[(1, 'GET'), (2, 'POST'), (3, 'DELETE'), (4, 'PUT'), (5, 'PATCH'), (6, 'OPTIONS')], help_text='方法', verbose_name='方法类型'),
        ),
    ]
