# Generated by Django 5.0.2 on 2024-02-24 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_permission_method_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='parent_menu',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='url_name',
        ),
        migrations.AddField(
            model_name='menu',
            name='children',
            field=models.ForeignKey(blank=True, help_text='子菜单', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_menu', to='user.menu', verbose_name='子菜单'),
        ),
        migrations.AddField(
            model_name='menu',
            name='path',
            field=models.CharField(default='', help_text='路径', max_length=50, verbose_name='路径'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='icon',
            field=models.CharField(help_text='图标', max_length=50, verbose_name='图标'),
        ),
    ]
