# Generated by Django 5.0.2 on 2024-02-24 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_remove_menu_children_menu_parent_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='parent_menu',
        ),
        migrations.AddField(
            model_name='menu',
            name='sub_menu',
            field=models.ForeignKey(blank=True, help_text='上级菜单', null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.menu', verbose_name='上级菜单'),
        ),
    ]
