# Generated by Django 5.0.3 on 2024-03-16 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_remove_menu_parent_menu_menu_sub_menu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'verbose_name': '权限', 'verbose_name_plural': '权限'},
        ),
        migrations.RemoveField(
            model_name='role',
            name='role_type',
        ),
        migrations.AddField(
            model_name='role',
            name='name',
            field=models.CharField(default='', help_text='角色名称', max_length=30, verbose_name='角色名称'),
        ),
    ]
