# Generated by Django 5.0.3 on 2024-03-16 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_alter_permission_options_remove_role_role_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='icon',
            field=models.CharField(default='default.jpg', help_text='用户头像', max_length=50, verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='role',
            name='permission',
            field=models.ManyToManyField(related_name='role', to='user.permission', verbose_name='权限'),
        ),
    ]
