# Generated by Django 5.0.3 on 2024-03-16 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_userprofile_icon_alter_role_permission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='icon',
            new_name='avatar',
        ),
    ]
