# Generated by Django 5.0.3 on 2024-04-01 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='标题', max_length=40, null=True, verbose_name='标题')),
                ('percentage', models.IntegerField(default=0, help_text='进度', verbose_name='进度')),
                ('content', models.CharField(help_text='内容', max_length=300, null=True, verbose_name='内容')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '功能',
                'verbose_name_plural': '功能',
            },
        ),
    ]
