# Generated by Django 5.0.3 on 2024-04-01 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='add_time',
            new_name='public_date',
        ),
    ]
