# Generated by Django 5.0.3 on 2024-04-12 00:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='public_date',
            field=models.DateField(default=datetime.date.today, help_text='添加时间', verbose_name='添加时间'),
        ),
    ]
