#!/usr/bin/env python
# encoding: utf-8

menu_datas = [
    {
        "menu_id": 1000,
        "sub_menu": None,
        "path": "/profile",
        "component": "profile",
        "hidden": False,
        "redirect": None,
        "name": "profile",
        "title": "profile",
        "icon": "user",
    },
    {
        "menu_id": 2000,
        "sub_menu": None,
        "path": "/user",
        "component": "layout",
        "hidden": False,
        "redirect": "userManage",
        "name": "userManage",
        "title": "user",
        "icon": "personnel",
    },
    {
        "menu_id": 2001,
        "sub_menu": 2000,
        "path": "/user/manage",
        "component": "user-manage",
        "hidden": False,
        "redirect": None,
        "name": None,
        "title": "userManage",
        "icon": "personnel-manage",
    },
    {
        "menu_id": 2002,
        "sub_menu": 2000,
        "path": "/user/info/:id",
        "component": "user-info",
        "hidden": True,
        "redirect": None,
        "name": None,
        "title": "userInfo",
        "icon": None,
    },
    {
        "menu_id": 2003,
        "sub_menu": 2000,
        "path": "/user/import",
        "component": "import",
        "hidden": True,
        "redirect": None,
        "name": "import",
        "title": "excelImport",
        "icon": None,
    },
    {
        "menu_id": 2004,
        "sub_menu": 2000,
        "path": "/user/role",
        "component": "role-list",
        "hidden": False,
        "redirect": None,
        "name": None,
        "title": "roleList",
        "icon": "role",
    },
    {
        "menu_id": 2005,
        "sub_menu": 2000,
        "path": "/user/permission",
        "component": "permission-list",
        "hidden": False,
        "redirect": None,
        "name": None,
        "title": "permissionList",
        "icon": "permission",
    },
    # 业务
    {
        "menu_id": 3000,
        "sub_menu": None,
        "path": "/article",
        "component": "layout",
        "hidden": False,
        "redirect": "/article/ranking",
        "name": "articleRanking",
        "title": "article",
        "icon": "article",
    },
    {
        "menu_id": 3001,
        "sub_menu": 3000,
        "path": "/article/:id",
        "component": "article-detail",
        "hidden": True,
        "redirect": None,
        "name": None,
        "title": "articleDetail",
        "icon": None,
    },
    {
        "menu_id": 3002,
        "sub_menu": 3000,
        "path": "/article/create",
        "component": "article-create",
        "hidden": False,
        "redirect": None,
        "name": None,
        "title": "articleCreate",
        "icon": "article-create",
    },
    {
        "menu_id": 3003,
        "sub_menu": 3000,
        "path": "/article/ranking",
        "component": "article-ranking",
        "hidden": False,
        "redirect": "/article/ranking",
        "name": "articleRanking",
        "title": "articleRanking",
        "icon": "article-ranking",
    },
]
