#!/usr/bin/env python
# encoding: utf-8

"""
  RoleListRouter,
  UserManageRouter,
  PermissionListRouter,
  ArticleCreaterRouter,
  ArticleRouter
"""
menu_datas = [
    {
        "menu_id": 1000,
        "sub_menu": None,
        "path": "/user",
        "component": "layout",
        "redirect": "userManage",
        "name": "sysManage",
        "title": "sysManage",
        "icon": "system",
    },
    {
        "menu_id": 2000,
        "sub_menu": None,
        "path": "/user",
        "component": "layout",
        "redirect": "userManage",
        "name": "userManage",
        "title": "user",
        "icon": "personnel",
    },
    {
        "menu_id": 2001,
        "sub_menu": 2000,
        "path": "/user/manage",
        "component": "user-manage/index",
        "redirect": None,
        "name": None,
        "title": "userManage",
        "icon": "personnel-manage",
    },
    {
        "menu_id": 2002,
        "sub_menu": 2000,
        "path": "/user/info/:id",
        "component": "user-info/index",
        "redirect": None,
        "name": None,
        "title": "userInfo",
        "icon": None,
    },
    {
        "menu_id": 2003,
        "sub_menu": 2000,
        "path": "/user/import",
        "component": "import/index",
        "redirect": None,
        "name": "import",
        "title": "excelImport",
        "icon": None,
    },
    {
        "menu_id": 2004,
        "sub_menu": 2000,
        "path": "/user/role",
        "component": "role-list/index",
        "redirect": None,
        "name": None,
        "title": "roleList",
        "icon": "role",
    },
    {
        "menu_id": 2005,
        "sub_menu": 2000,
        "path": "/user/permission",
        "component": "permission-list/index",
        "redirect": None,
        "name": None,
        "title": "permissionList",
        "icon": "permission",
    },
    {
        "menu_id": 2005,
        "sub_menu": 2000,
        "path": "/user/permission",
        "component": "permission-list/index",
        "redirect": None,
        "name": None,
        "title": "permissionList",
        "icon": "permission",
    },
    # 业务
    {
        "menu_id": 3000,
        "sub_menu": None,
        "path": "/article",
        "component": "layout",
        "redirect": "/article/ranking",
        "name": "articleRanking",
        "title": "article",
        "icon": "article",
    },
    {
        "menu_id": 3001,
        "sub_menu": 3000,
        "path": "/article/:id",
        "component": "article-detail/index",
        "redirect": None,
        "name": None,
        "title": "articleDetail",
        "icon": None,
    },
    {
        "menu_id": 3002,
        "sub_menu": 3000,
        "path": "/article/create",
        "component": "article-create/index",
        "redirect": None,
        "name": None,
        "title": "articleCreate",
        "icon": "article-create",
    },
]
